### ISSUE TITLE
Why are you unwrapping the Promise from pg?

### ISSUE THREAD

**Issue by eudaimos** [dmanjunath/node-redshift#13]
In your query code you are importing Bluebird simply to handle the returned promise, unwrap it, and then use a callback style.

Why?

**Comment by vitaly-t** [comment]
'Cos that's what people do when they do not understand how to use promises.

**Comment by dmanjunath** [comment]
@eudaimos @vitaly-t I personally don't like using promises, but that doesn't mean I don't want to stop others from using it- see https://github.com/dmanjunath/node-redshift/pull/11

**Comment by vitaly-t** [comment]
> personally don't like using promises

This no longer bodes well for public libraries, ever since Node.js 7.6.0 that now supports `async/await` syntax by default, which works natively with promises, which is a hugely important feature.

**Comment by dmanjunath** [comment]
@vitaly-t I prefer async/await too but since it just got off --harmony, and not to mention node 7 is not a LTS release I don't want to write the query code using async/await without a transpiler. But if someone's using async/await the query function should still work as it is right now with full support for promises.

**Comment by vitaly-t** [comment]
>  I don't want to write the query code using async/await without a transpiler

This wasn't what I suggested. I simply pointed out that if you provide a promise-based interface, then anyone who already uses `async/away` can use such API natively, as `async/await` maps into promises directly.

**Comment by dmanjunath** [comment]
I'm sorry @vitaly-t  I'm not sure what youre trying to say. If you're saying that I should have implemented the query function with promises, yeah I'm going to do that soon. I just switched this one function over to promises real quick because I was traveling but I wanted to give support to the issue on the PR. I probably will do that refactor when I implement the rest of the ORM functions with promise support. But even as it stands now, the query function should be fully compliant with promises directly so they can use async/await immediately

If you're saying that they can bypass this whole module and use the pg module directly because it supports promises yeah that's the user's choice, I can't say anything about that.

**Comment by ChrisCates** [comment]
LOL I can't believe you guys are roasting @dmanjunath when I highly doubt y'all have used a Systems Level language before.

**Comment by vitaly-t** [comment]
Roasting? No worries, we are flipping sides :smile:

**Comment by dmanjunath** [comment]
@ChrisCates thanks for the backup haha. But this is getting off topic very quickly. Unless there's a concrete issue or code improvement I'm closing this issue.
